config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'posts#index'

  resources :posts, except: [:delete, :update, :edit]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def index
    @posts = Post.all
  end

  def show; end

  def destroy
    # @post = Post.find(params[:id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :user_id)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def new
    # useless method
  end

  def create
    # useless method
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    # useless method
  end

  def create
    # useless method
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def user_post?
    post.user.id == current_user.id
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://kit.fontawesome.com/fdaa9ad399.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="w-100 alert alert-warning d-flex justify-content-center pb-0 m-0">
        <p class="notice"> <%= notice %> </p>
      </div>
    <% end %>

    <% if flash[:alert]%>
      <div class="w-100 alert alert-danger d-flex justify-content-center pb-0 m-0">
        <p class="alert"> <%= alert %> </p>
      </div>
    <% end %>

    <nav class="navbar px-5 bg-dark">

      <div class="navbar-brand pb-0">
        <h1 class="h3"><%= link_to "Members Only", root_path, class: "navbar-logo-edit text-light" %></h1>
      </div>

      <ul class="navbar-nav">
        <% if user_signed_in? %>

          <div class="user_navbar d-flex">
            <li class="nav-item d-flex align-items-center">
              <%= link_to "Make a new post", new_post_path, class: "btn btn-outline-warning mx-3 no-link px-3" %>
            </li>
            <li class="nav-item d-flex align-items-center">
              <%= link_to current_user.name, edit_user_registration_path, class: "text-light no-link px-3" %>
            </li>
            <li>
              <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link btn btn-outline-light mx-3 px-3" %>
            </li>
          </div>

        <% else %>

          <div class="user_navbar d-flex">
            <li class="nav-item d-flex align-items-center">
              <span class=""><%= link_to "Sign in", new_user_session_path, class: "no-link btn btn-outline-light nav-link px-3" %></span>
            </li>
            <li class="px-2">
              <%= link_to "Sign up", new_user_registration_path, class: "nav-link btn btn-light mx-3 px-3" %>
            </li>
          </div>

        <% end %>
      </ul>

    </nav>

    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/index.html.erb
<div class="container">
  <h1 class="text-dark py-3">Posts</h1>

  <% @posts.each do |post| %>
    <div class="border rounded p-0 mb-3">
        <div class="p-3">
          <div class="p-3 bg-light">
            <p class="mb-0 h3 text-dark"><%= link_to post.title, post_path(post), class: "no-link text-dark" %></p>
          </div>
          <div class=" border-top p-3">
            <p class="mb-0 text-dark"><%= post.content %></p>
          </div>
        </div>
        <% if user_signed_in? %>
          <div class="px-3">
            <p class="bg-light border-top rounded py-3"><small class="px-3 text-secondary">Posted by:</small><%= post.user.name %></p>
          </div>

          <% if post.user.id == current_user.id %>
            <div class="mb-3 ml-3">
              <%= link_to post, method: :delete, data: { confirm: "Are you sure??" } do %>
                <i class="fas fa-trash-alt text-dark"></i>
              <% end %>
            </div>
          <% end %>
        <% end %>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="container">

  <h1 class="h1 my-3 text-dark">Create post</h1>

  <%= form_for @post do |f| %>
    <div class="form-group">
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="">
        <%= f.text_area :content, class: "form-control" %>
    </div>
    <%= f.submit "Post", class: "btn btn-primary mt-3 px-3" %>
  <% end %>

</div>

app/views/posts/show.html.erb
<div class="container mt-3">
  <div class="border rounded p-0 mb-3">
    <div class="p-3">
      <div class="p-3 bg-light">
        <p class="mb-0 h3 text-dark"><%= @post.title %></p>
      </div>
      <div class=" border-top p-3">
        <p class="mb-0 text-dark"><%= @post.content %></p>
      </div>
    </div>
    <% if user_signed_in? %>
      <div class="px-3">
        <p class="bg-light border-top rounded py-3"><small class="px-3 text-secondary">Posted by:</small><%= @post.user.name %></p>
      </div>
    <% end %>
  </div>
</div>